// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package october2024november2024

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

// defaultVulnrichmentParamsResponse is returned by defaultVulnrichmentParams on success.
type defaultVulnrichmentParamsResponse struct {
	UpdateVulnerability *defaultVulnrichmentParamsUpdateVulnerabilityUpdateVulnerabilityPayload `json:"updateVulnerability"`
}

// GetUpdateVulnerability returns defaultVulnrichmentParamsResponse.UpdateVulnerability, and is useful for accessing the field via an interface.
func (v *defaultVulnrichmentParamsResponse) GetUpdateVulnerability() *defaultVulnrichmentParamsUpdateVulnerabilityUpdateVulnerabilityPayload {
	return v.UpdateVulnerability
}

// defaultVulnrichmentParamsUpdateVulnerabilityUpdateVulnerabilityPayload includes the requested fields of the GraphQL type UpdateVulnerabilityPayload.
type defaultVulnrichmentParamsUpdateVulnerabilityUpdateVulnerabilityPayload struct {
	NumUids *int `json:"numUids"`
}

// GetNumUids returns defaultVulnrichmentParamsUpdateVulnerabilityUpdateVulnerabilityPayload.NumUids, and is useful for accessing the field via an interface.
func (v *defaultVulnrichmentParamsUpdateVulnerabilityUpdateVulnerabilityPayload) GetNumUids() *int {
	return v.NumUids
}

// The query or mutation executed by defaultVulnrichmentParams.
const defaultVulnrichmentParams_Operation = `
mutation defaultVulnrichmentParams {
	updateVulnerability(input: {set:{exploitation:"",automatable:"",technicalImpact:""},filter:{has:id}}) {
		numUids
	}
}
`

func defaultVulnrichmentParams(
	ctx_ context.Context,
	client_ graphql.Client,
) (*defaultVulnrichmentParamsResponse, error) {
	req_ := &graphql.Request{
		OpName: "defaultVulnrichmentParams",
		Query:  defaultVulnrichmentParams_Operation,
	}
	var err_ error

	var data_ defaultVulnrichmentParamsResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}
