// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package june2024v2

import (
	"context"
	"time"

	"github.com/Khan/genqlient/graphql"
)

// QueryAllArtifactScanDataQueryArtifactScanData includes the requested fields of the GraphQL type ArtifactScanData.
type QueryAllArtifactScanDataQueryArtifactScanData struct {
	SbomUrl                            string `json:"sbomUrl"`
	ArtifactLicenseScanUrl             string `json:"artifactLicenseScanUrl"`
	ArtifactSecretScanUrl              string `json:"artifactSecretScanUrl"`
	SourceLicenseScanUrl               string `json:"sourceLicenseScanUrl"`
	SourceSecretScanUrl                string `json:"sourceSecretScanUrl"`
	SourceScorecardScanUrl             string `json:"sourceScorecardScanUrl"`
	SourceSemgrepHighSeverityScanUrl   string `json:"sourceSemgrepHighSeverityScanUrl"`
	SourceSemgrepMediumSeverityScanUrl string `json:"sourceSemgrepMediumSeverityScanUrl"`
	SourceSemgrepLowSeverityScanUrl    string `json:"sourceSemgrepLowSeverityScanUrl"`
	SourceSnykScanUrl                  string `json:"sourceSnykScanUrl"`
	VirusTotalUrlScan                  string `json:"virusTotalUrlScan"`
	Id                                 string `json:"id"`
}

// GetSbomUrl returns QueryAllArtifactScanDataQueryArtifactScanData.SbomUrl, and is useful for accessing the field via an interface.
func (v *QueryAllArtifactScanDataQueryArtifactScanData) GetSbomUrl() string { return v.SbomUrl }

// GetArtifactLicenseScanUrl returns QueryAllArtifactScanDataQueryArtifactScanData.ArtifactLicenseScanUrl, and is useful for accessing the field via an interface.
func (v *QueryAllArtifactScanDataQueryArtifactScanData) GetArtifactLicenseScanUrl() string {
	return v.ArtifactLicenseScanUrl
}

// GetArtifactSecretScanUrl returns QueryAllArtifactScanDataQueryArtifactScanData.ArtifactSecretScanUrl, and is useful for accessing the field via an interface.
func (v *QueryAllArtifactScanDataQueryArtifactScanData) GetArtifactSecretScanUrl() string {
	return v.ArtifactSecretScanUrl
}

// GetSourceLicenseScanUrl returns QueryAllArtifactScanDataQueryArtifactScanData.SourceLicenseScanUrl, and is useful for accessing the field via an interface.
func (v *QueryAllArtifactScanDataQueryArtifactScanData) GetSourceLicenseScanUrl() string {
	return v.SourceLicenseScanUrl
}

// GetSourceSecretScanUrl returns QueryAllArtifactScanDataQueryArtifactScanData.SourceSecretScanUrl, and is useful for accessing the field via an interface.
func (v *QueryAllArtifactScanDataQueryArtifactScanData) GetSourceSecretScanUrl() string {
	return v.SourceSecretScanUrl
}

// GetSourceScorecardScanUrl returns QueryAllArtifactScanDataQueryArtifactScanData.SourceScorecardScanUrl, and is useful for accessing the field via an interface.
func (v *QueryAllArtifactScanDataQueryArtifactScanData) GetSourceScorecardScanUrl() string {
	return v.SourceScorecardScanUrl
}

// GetSourceSemgrepHighSeverityScanUrl returns QueryAllArtifactScanDataQueryArtifactScanData.SourceSemgrepHighSeverityScanUrl, and is useful for accessing the field via an interface.
func (v *QueryAllArtifactScanDataQueryArtifactScanData) GetSourceSemgrepHighSeverityScanUrl() string {
	return v.SourceSemgrepHighSeverityScanUrl
}

// GetSourceSemgrepMediumSeverityScanUrl returns QueryAllArtifactScanDataQueryArtifactScanData.SourceSemgrepMediumSeverityScanUrl, and is useful for accessing the field via an interface.
func (v *QueryAllArtifactScanDataQueryArtifactScanData) GetSourceSemgrepMediumSeverityScanUrl() string {
	return v.SourceSemgrepMediumSeverityScanUrl
}

// GetSourceSemgrepLowSeverityScanUrl returns QueryAllArtifactScanDataQueryArtifactScanData.SourceSemgrepLowSeverityScanUrl, and is useful for accessing the field via an interface.
func (v *QueryAllArtifactScanDataQueryArtifactScanData) GetSourceSemgrepLowSeverityScanUrl() string {
	return v.SourceSemgrepLowSeverityScanUrl
}

// GetSourceSnykScanUrl returns QueryAllArtifactScanDataQueryArtifactScanData.SourceSnykScanUrl, and is useful for accessing the field via an interface.
func (v *QueryAllArtifactScanDataQueryArtifactScanData) GetSourceSnykScanUrl() string {
	return v.SourceSnykScanUrl
}

// GetVirusTotalUrlScan returns QueryAllArtifactScanDataQueryArtifactScanData.VirusTotalUrlScan, and is useful for accessing the field via an interface.
func (v *QueryAllArtifactScanDataQueryArtifactScanData) GetVirusTotalUrlScan() string {
	return v.VirusTotalUrlScan
}

// GetId returns QueryAllArtifactScanDataQueryArtifactScanData.Id, and is useful for accessing the field via an interface.
func (v *QueryAllArtifactScanDataQueryArtifactScanData) GetId() string { return v.Id }

// QueryAllArtifactScanDataResponse is returned by QueryAllArtifactScanData on success.
type QueryAllArtifactScanDataResponse struct {
	QueryArtifactScanData []*QueryAllArtifactScanDataQueryArtifactScanData `json:"queryArtifactScanData"`
}

// GetQueryArtifactScanData returns QueryAllArtifactScanDataResponse.QueryArtifactScanData, and is useful for accessing the field via an interface.
func (v *QueryAllArtifactScanDataResponse) GetQueryArtifactScanData() []*QueryAllArtifactScanDataQueryArtifactScanData {
	return v.QueryArtifactScanData
}

// QueryExistingIntegratorsQueryIntegrator includes the requested fields of the GraphQL type Integrator.
type QueryExistingIntegratorsQueryIntegrator struct {
	Organization *QueryExistingIntegratorsQueryIntegratorOrganization `json:"organization"`
	Category     string                                               `json:"category"`
	Credentials  *QueryExistingIntegratorsQueryIntegratorCredentials  `json:"credentials"`
	CreatedAt    *time.Time                                           `json:"createdAt"`
	UpdatedAt    *time.Time                                           `json:"updatedAt"`
	Type         string                                               `json:"type"`
	Name         string                                               `json:"name"`
}

// GetOrganization returns QueryExistingIntegratorsQueryIntegrator.Organization, and is useful for accessing the field via an interface.
func (v *QueryExistingIntegratorsQueryIntegrator) GetOrganization() *QueryExistingIntegratorsQueryIntegratorOrganization {
	return v.Organization
}

// GetCategory returns QueryExistingIntegratorsQueryIntegrator.Category, and is useful for accessing the field via an interface.
func (v *QueryExistingIntegratorsQueryIntegrator) GetCategory() string { return v.Category }

// GetCredentials returns QueryExistingIntegratorsQueryIntegrator.Credentials, and is useful for accessing the field via an interface.
func (v *QueryExistingIntegratorsQueryIntegrator) GetCredentials() *QueryExistingIntegratorsQueryIntegratorCredentials {
	return v.Credentials
}

// GetCreatedAt returns QueryExistingIntegratorsQueryIntegrator.CreatedAt, and is useful for accessing the field via an interface.
func (v *QueryExistingIntegratorsQueryIntegrator) GetCreatedAt() *time.Time { return v.CreatedAt }

// GetUpdatedAt returns QueryExistingIntegratorsQueryIntegrator.UpdatedAt, and is useful for accessing the field via an interface.
func (v *QueryExistingIntegratorsQueryIntegrator) GetUpdatedAt() *time.Time { return v.UpdatedAt }

// GetType returns QueryExistingIntegratorsQueryIntegrator.Type, and is useful for accessing the field via an interface.
func (v *QueryExistingIntegratorsQueryIntegrator) GetType() string { return v.Type }

// GetName returns QueryExistingIntegratorsQueryIntegrator.Name, and is useful for accessing the field via an interface.
func (v *QueryExistingIntegratorsQueryIntegrator) GetName() string { return v.Name }

// QueryExistingIntegratorsQueryIntegratorCredentials includes the requested fields of the GraphQL type Credentials.
type QueryExistingIntegratorsQueryIntegratorCredentials struct {
	Data string `json:"data"`
}

// GetData returns QueryExistingIntegratorsQueryIntegratorCredentials.Data, and is useful for accessing the field via an interface.
func (v *QueryExistingIntegratorsQueryIntegratorCredentials) GetData() string { return v.Data }

// QueryExistingIntegratorsQueryIntegratorOrganization includes the requested fields of the GraphQL type Organization.
type QueryExistingIntegratorsQueryIntegratorOrganization struct {
	// id is randomly assigned
	Id string `json:"id"`
}

// GetId returns QueryExistingIntegratorsQueryIntegratorOrganization.Id, and is useful for accessing the field via an interface.
func (v *QueryExistingIntegratorsQueryIntegratorOrganization) GetId() string { return v.Id }

// QueryExistingIntegratorsResponse is returned by QueryExistingIntegrators on success.
type QueryExistingIntegratorsResponse struct {
	QueryIntegrator []*QueryExistingIntegratorsQueryIntegrator `json:"queryIntegrator"`
}

// GetQueryIntegrator returns QueryExistingIntegratorsResponse.QueryIntegrator, and is useful for accessing the field via an interface.
func (v *QueryExistingIntegratorsResponse) GetQueryIntegrator() []*QueryExistingIntegratorsQueryIntegrator {
	return v.QueryIntegrator
}

// The query or mutation executed by QueryAllArtifactScanData.
const QueryAllArtifactScanData_Operation = `
query QueryAllArtifactScanData {
	queryArtifactScanData {
		sbomUrl
		artifactLicenseScanUrl
		artifactSecretScanUrl
		sourceLicenseScanUrl
		sourceSecretScanUrl
		sourceScorecardScanUrl
		sourceSemgrepHighSeverityScanUrl
		sourceSemgrepMediumSeverityScanUrl
		sourceSemgrepLowSeverityScanUrl
		sourceSnykScanUrl
		virusTotalUrlScan
		id
	}
}
`

func QueryAllArtifactScanData(
	ctx_ context.Context,
	client_ graphql.Client,
) (*QueryAllArtifactScanDataResponse, error) {
	req_ := &graphql.Request{
		OpName: "QueryAllArtifactScanData",
		Query:  QueryAllArtifactScanData_Operation,
	}
	var err_ error

	var data_ QueryAllArtifactScanDataResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}

// The query or mutation executed by QueryExistingIntegrators.
const QueryExistingIntegrators_Operation = `
query QueryExistingIntegrators {
	queryIntegrator {
		organization {
			id
		}
		category
		credentials {
			data
		}
		createdAt
		updatedAt
		type
		name
	}
}
`

func QueryExistingIntegrators(
	ctx_ context.Context,
	client_ graphql.Client,
) (*QueryExistingIntegratorsResponse, error) {
	req_ := &graphql.Request{
		OpName: "QueryExistingIntegrators",
		Query:  QueryExistingIntegrators_Operation,
	}
	var err_ error

	var data_ QueryExistingIntegratorsResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}
