// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package june2024v2

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

// QueryAllArtifactScanDataQueryArtifactScanData includes the requested fields of the GraphQL type ArtifactScanData.
type QueryAllArtifactScanDataQueryArtifactScanData struct {
	SbomUrl                            string `json:"sbomUrl"`
	ArtifactLicenseScanUrl             string `json:"artifactLicenseScanUrl"`
	ArtifactSecretScanUrl              string `json:"artifactSecretScanUrl"`
	SourceLicenseScanUrl               string `json:"sourceLicenseScanUrl"`
	SourceSecretScanUrl                string `json:"sourceSecretScanUrl"`
	SourceScorecardScanUrl             string `json:"sourceScorecardScanUrl"`
	SourceSemgrepHighSeverityScanUrl   string `json:"sourceSemgrepHighSeverityScanUrl"`
	SourceSemgrepMediumSeverityScanUrl string `json:"sourceSemgrepMediumSeverityScanUrl"`
	SourceSemgrepLowSeverityScanUrl    string `json:"sourceSemgrepLowSeverityScanUrl"`
	Id                                 string `json:"id"`
}

// GetSbomUrl returns QueryAllArtifactScanDataQueryArtifactScanData.SbomUrl, and is useful for accessing the field via an interface.
func (v *QueryAllArtifactScanDataQueryArtifactScanData) GetSbomUrl() string { return v.SbomUrl }

// GetArtifactLicenseScanUrl returns QueryAllArtifactScanDataQueryArtifactScanData.ArtifactLicenseScanUrl, and is useful for accessing the field via an interface.
func (v *QueryAllArtifactScanDataQueryArtifactScanData) GetArtifactLicenseScanUrl() string {
	return v.ArtifactLicenseScanUrl
}

// GetArtifactSecretScanUrl returns QueryAllArtifactScanDataQueryArtifactScanData.ArtifactSecretScanUrl, and is useful for accessing the field via an interface.
func (v *QueryAllArtifactScanDataQueryArtifactScanData) GetArtifactSecretScanUrl() string {
	return v.ArtifactSecretScanUrl
}

// GetSourceLicenseScanUrl returns QueryAllArtifactScanDataQueryArtifactScanData.SourceLicenseScanUrl, and is useful for accessing the field via an interface.
func (v *QueryAllArtifactScanDataQueryArtifactScanData) GetSourceLicenseScanUrl() string {
	return v.SourceLicenseScanUrl
}

// GetSourceSecretScanUrl returns QueryAllArtifactScanDataQueryArtifactScanData.SourceSecretScanUrl, and is useful for accessing the field via an interface.
func (v *QueryAllArtifactScanDataQueryArtifactScanData) GetSourceSecretScanUrl() string {
	return v.SourceSecretScanUrl
}

// GetSourceScorecardScanUrl returns QueryAllArtifactScanDataQueryArtifactScanData.SourceScorecardScanUrl, and is useful for accessing the field via an interface.
func (v *QueryAllArtifactScanDataQueryArtifactScanData) GetSourceScorecardScanUrl() string {
	return v.SourceScorecardScanUrl
}

// GetSourceSemgrepHighSeverityScanUrl returns QueryAllArtifactScanDataQueryArtifactScanData.SourceSemgrepHighSeverityScanUrl, and is useful for accessing the field via an interface.
func (v *QueryAllArtifactScanDataQueryArtifactScanData) GetSourceSemgrepHighSeverityScanUrl() string {
	return v.SourceSemgrepHighSeverityScanUrl
}

// GetSourceSemgrepMediumSeverityScanUrl returns QueryAllArtifactScanDataQueryArtifactScanData.SourceSemgrepMediumSeverityScanUrl, and is useful for accessing the field via an interface.
func (v *QueryAllArtifactScanDataQueryArtifactScanData) GetSourceSemgrepMediumSeverityScanUrl() string {
	return v.SourceSemgrepMediumSeverityScanUrl
}

// GetSourceSemgrepLowSeverityScanUrl returns QueryAllArtifactScanDataQueryArtifactScanData.SourceSemgrepLowSeverityScanUrl, and is useful for accessing the field via an interface.
func (v *QueryAllArtifactScanDataQueryArtifactScanData) GetSourceSemgrepLowSeverityScanUrl() string {
	return v.SourceSemgrepLowSeverityScanUrl
}

// GetId returns QueryAllArtifactScanDataQueryArtifactScanData.Id, and is useful for accessing the field via an interface.
func (v *QueryAllArtifactScanDataQueryArtifactScanData) GetId() string { return v.Id }

// QueryAllArtifactScanDataResponse is returned by QueryAllArtifactScanData on success.
type QueryAllArtifactScanDataResponse struct {
	QueryArtifactScanData []*QueryAllArtifactScanDataQueryArtifactScanData `json:"queryArtifactScanData"`
}

// GetQueryArtifactScanData returns QueryAllArtifactScanDataResponse.QueryArtifactScanData, and is useful for accessing the field via an interface.
func (v *QueryAllArtifactScanDataResponse) GetQueryArtifactScanData() []*QueryAllArtifactScanDataQueryArtifactScanData {
	return v.QueryArtifactScanData
}

// The query or mutation executed by QueryAllArtifactScanData.
const QueryAllArtifactScanData_Operation = `
query QueryAllArtifactScanData {
	queryArtifactScanData {
		sbomUrl
		artifactLicenseScanUrl
		artifactSecretScanUrl
		sourceLicenseScanUrl
		sourceSecretScanUrl
		sourceScorecardScanUrl
		sourceSemgrepHighSeverityScanUrl
		sourceSemgrepMediumSeverityScanUrl
		sourceSemgrepLowSeverityScanUrl
		id
	}
}
`

func QueryAllArtifactScanData(
	ctx_ context.Context,
	client_ graphql.Client,
) (*QueryAllArtifactScanDataResponse, error) {
	req_ := &graphql.Request{
		OpName: "QueryAllArtifactScanData",
		Query:  QueryAllArtifactScanData_Operation,
	}
	var err_ error

	var data_ QueryAllArtifactScanDataResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}
