// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package august2024august2024v2

import (
	"context"
	"time"

	"github.com/Khan/genqlient/graphql"
)

// DeleteArtifactScanDataDeleteArtifactScanDataDeleteArtifactScanDataPayload includes the requested fields of the GraphQL type DeleteArtifactScanDataPayload.
type DeleteArtifactScanDataDeleteArtifactScanDataDeleteArtifactScanDataPayload struct {
	Msg     string `json:"msg"`
	NumUids *int   `json:"numUids"`
}

// GetMsg returns DeleteArtifactScanDataDeleteArtifactScanDataDeleteArtifactScanDataPayload.Msg, and is useful for accessing the field via an interface.
func (v *DeleteArtifactScanDataDeleteArtifactScanDataDeleteArtifactScanDataPayload) GetMsg() string {
	return v.Msg
}

// GetNumUids returns DeleteArtifactScanDataDeleteArtifactScanDataDeleteArtifactScanDataPayload.NumUids, and is useful for accessing the field via an interface.
func (v *DeleteArtifactScanDataDeleteArtifactScanDataDeleteArtifactScanDataPayload) GetNumUids() *int {
	return v.NumUids
}

// DeleteArtifactScanDataForInprogressDeleteArtifactScanDataDeleteArtifactScanDataPayload includes the requested fields of the GraphQL type DeleteArtifactScanDataPayload.
type DeleteArtifactScanDataForInprogressDeleteArtifactScanDataDeleteArtifactScanDataPayload struct {
	NumUids *int `json:"numUids"`
}

// GetNumUids returns DeleteArtifactScanDataForInprogressDeleteArtifactScanDataDeleteArtifactScanDataPayload.NumUids, and is useful for accessing the field via an interface.
func (v *DeleteArtifactScanDataForInprogressDeleteArtifactScanDataDeleteArtifactScanDataPayload) GetNumUids() *int {
	return v.NumUids
}

// DeleteArtifactScanDataForInprogressResponse is returned by DeleteArtifactScanDataForInprogress on success.
type DeleteArtifactScanDataForInprogressResponse struct {
	DeleteArtifactScanData *DeleteArtifactScanDataForInprogressDeleteArtifactScanDataDeleteArtifactScanDataPayload `json:"deleteArtifactScanData"`
}

// GetDeleteArtifactScanData returns DeleteArtifactScanDataForInprogressResponse.DeleteArtifactScanData, and is useful for accessing the field via an interface.
func (v *DeleteArtifactScanDataForInprogressResponse) GetDeleteArtifactScanData() *DeleteArtifactScanDataForInprogressDeleteArtifactScanDataDeleteArtifactScanDataPayload {
	return v.DeleteArtifactScanData
}

// DeleteArtifactScanDataNotHaveArtifactDeleteArtifactScanDataDeleteArtifactScanDataPayload includes the requested fields of the GraphQL type DeleteArtifactScanDataPayload.
type DeleteArtifactScanDataNotHaveArtifactDeleteArtifactScanDataDeleteArtifactScanDataPayload struct {
	NumUids *int `json:"numUids"`
}

// GetNumUids returns DeleteArtifactScanDataNotHaveArtifactDeleteArtifactScanDataDeleteArtifactScanDataPayload.NumUids, and is useful for accessing the field via an interface.
func (v *DeleteArtifactScanDataNotHaveArtifactDeleteArtifactScanDataDeleteArtifactScanDataPayload) GetNumUids() *int {
	return v.NumUids
}

// DeleteArtifactScanDataNotHaveArtifactResponse is returned by DeleteArtifactScanDataNotHaveArtifact on success.
type DeleteArtifactScanDataNotHaveArtifactResponse struct {
	DeleteArtifactScanData *DeleteArtifactScanDataNotHaveArtifactDeleteArtifactScanDataDeleteArtifactScanDataPayload `json:"deleteArtifactScanData"`
}

// GetDeleteArtifactScanData returns DeleteArtifactScanDataNotHaveArtifactResponse.DeleteArtifactScanData, and is useful for accessing the field via an interface.
func (v *DeleteArtifactScanDataNotHaveArtifactResponse) GetDeleteArtifactScanData() *DeleteArtifactScanDataNotHaveArtifactDeleteArtifactScanDataDeleteArtifactScanDataPayload {
	return v.DeleteArtifactScanData
}

// DeleteArtifactScanDataResponse is returned by DeleteArtifactScanData on success.
type DeleteArtifactScanDataResponse struct {
	DeleteArtifactScanData *DeleteArtifactScanDataDeleteArtifactScanDataDeleteArtifactScanDataPayload `json:"deleteArtifactScanData"`
}

// GetDeleteArtifactScanData returns DeleteArtifactScanDataResponse.DeleteArtifactScanData, and is useful for accessing the field via an interface.
func (v *DeleteArtifactScanDataResponse) GetDeleteArtifactScanData() *DeleteArtifactScanDataDeleteArtifactScanDataDeleteArtifactScanDataPayload {
	return v.DeleteArtifactScanData
}

// GetArtifactRiskGetArtifactRisk includes the requested fields of the GraphQL type ArtifactRisk.
type GetArtifactRiskGetArtifactRisk struct {
	SourceCodeAlertsScore *int       `json:"sourceCodeAlertsScore"`
	BuildAlertsScore      *int       `json:"buildAlertsScore"`
	ArtifactAlertsScore   *int       `json:"artifactAlertsScore"`
	DeploymentAlertsScore *int       `json:"deploymentAlertsScore"`
	ArtifactRiskStatus    RiskStatus `json:"artifactRiskStatus"`
}

// GetSourceCodeAlertsScore returns GetArtifactRiskGetArtifactRisk.SourceCodeAlertsScore, and is useful for accessing the field via an interface.
func (v *GetArtifactRiskGetArtifactRisk) GetSourceCodeAlertsScore() *int {
	return v.SourceCodeAlertsScore
}

// GetBuildAlertsScore returns GetArtifactRiskGetArtifactRisk.BuildAlertsScore, and is useful for accessing the field via an interface.
func (v *GetArtifactRiskGetArtifactRisk) GetBuildAlertsScore() *int { return v.BuildAlertsScore }

// GetArtifactAlertsScore returns GetArtifactRiskGetArtifactRisk.ArtifactAlertsScore, and is useful for accessing the field via an interface.
func (v *GetArtifactRiskGetArtifactRisk) GetArtifactAlertsScore() *int { return v.ArtifactAlertsScore }

// GetDeploymentAlertsScore returns GetArtifactRiskGetArtifactRisk.DeploymentAlertsScore, and is useful for accessing the field via an interface.
func (v *GetArtifactRiskGetArtifactRisk) GetDeploymentAlertsScore() *int {
	return v.DeploymentAlertsScore
}

// GetArtifactRiskStatus returns GetArtifactRiskGetArtifactRisk.ArtifactRiskStatus, and is useful for accessing the field via an interface.
func (v *GetArtifactRiskGetArtifactRisk) GetArtifactRiskStatus() RiskStatus {
	return v.ArtifactRiskStatus
}

// GetArtifactRiskResponse is returned by GetArtifactRisk on success.
type GetArtifactRiskResponse struct {
	GetArtifactRisk *GetArtifactRiskGetArtifactRisk `json:"getArtifactRisk"`
}

// GetGetArtifactRisk returns GetArtifactRiskResponse.GetArtifactRisk, and is useful for accessing the field via an interface.
func (v *GetArtifactRiskResponse) GetGetArtifactRisk() *GetArtifactRiskGetArtifactRisk {
	return v.GetArtifactRisk
}

// GetArtifactScanDataIdQueryArtifactScanData includes the requested fields of the GraphQL type ArtifactScanData.
type GetArtifactScanDataIdQueryArtifactScanData struct {
	Id           string                                                  `json:"id"`
	ArtifactRisk *GetArtifactScanDataIdQueryArtifactScanDataArtifactRisk `json:"artifactRisk"`
}

// GetId returns GetArtifactScanDataIdQueryArtifactScanData.Id, and is useful for accessing the field via an interface.
func (v *GetArtifactScanDataIdQueryArtifactScanData) GetId() string { return v.Id }

// GetArtifactRisk returns GetArtifactScanDataIdQueryArtifactScanData.ArtifactRisk, and is useful for accessing the field via an interface.
func (v *GetArtifactScanDataIdQueryArtifactScanData) GetArtifactRisk() *GetArtifactScanDataIdQueryArtifactScanDataArtifactRisk {
	return v.ArtifactRisk
}

// GetArtifactScanDataIdQueryArtifactScanDataArtifactRisk includes the requested fields of the GraphQL type ArtifactRisk.
type GetArtifactScanDataIdQueryArtifactScanDataArtifactRisk struct {
	Id *string `json:"id"`
}

// GetId returns GetArtifactScanDataIdQueryArtifactScanDataArtifactRisk.Id, and is useful for accessing the field via an interface.
func (v *GetArtifactScanDataIdQueryArtifactScanDataArtifactRisk) GetId() *string { return v.Id }

// GetArtifactScanDataIdResponse is returned by GetArtifactScanDataId on success.
type GetArtifactScanDataIdResponse struct {
	QueryArtifactScanData []*GetArtifactScanDataIdQueryArtifactScanData `json:"queryArtifactScanData"`
}

// GetQueryArtifactScanData returns GetArtifactScanDataIdResponse.QueryArtifactScanData, and is useful for accessing the field via an interface.
func (v *GetArtifactScanDataIdResponse) GetQueryArtifactScanData() []*GetArtifactScanDataIdQueryArtifactScanData {
	return v.QueryArtifactScanData
}

// QueryArtifactScanDataRunHistoryQueryArtifactScanData includes the requested fields of the GraphQL type ArtifactScanData.
type QueryArtifactScanDataRunHistoryQueryArtifactScanData struct {
	ArtifactRunHistory []*QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistory `json:"artifactRunHistory"`
}

// GetArtifactRunHistory returns QueryArtifactScanDataRunHistoryQueryArtifactScanData.ArtifactRunHistory, and is useful for accessing the field via an interface.
func (v *QueryArtifactScanDataRunHistoryQueryArtifactScanData) GetArtifactRunHistory() []*QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistory {
	return v.ArtifactRunHistory
}

// QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistory includes the requested fields of the GraphQL type RunHistory.
type QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistory struct {
	Id                 *string                                                                                                    `json:"id"`
	PolicyId           string                                                                                                     `json:"policyId"`
	PolicyName         string                                                                                                     `json:"PolicyName"`
	Stage              string                                                                                                     `json:"Stage"`
	Artifact           string                                                                                                     `json:"Artifact"`
	ArtifactTag        string                                                                                                     `json:"ArtifactTag"`
	ArtifactSha        string                                                                                                     `json:"ArtifactSha"`
	CreatedAt          *time.Time                                                                                                 `json:"CreatedAt"`
	UpdatedAt          *time.Time                                                                                                 `json:"UpdatedAt"`
	DeployedAt         *time.Time                                                                                                 `json:"DeployedAt"`
	Hash               string                                                                                                     `json:"Hash"`
	Pass               *bool                                                                                                      `json:"Pass"`
	MetaData           string                                                                                                     `json:"MetaData"`
	ScheduledPolicy    *bool                                                                                                      `json:"scheduledPolicy"`
	DatasourceTool     string                                                                                                     `json:"DatasourceTool"`
	Status             string                                                                                                     `json:"Status"`
	SecurityIssue      *QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistorySecurityIssue                       `json:"securityIssue"`
	PolicyEnforcements *QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistoryPolicyEnforcementsPolicyEnforcement `json:"policyEnforcements"`
}

// GetId returns QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistory.Id, and is useful for accessing the field via an interface.
func (v *QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistory) GetId() *string {
	return v.Id
}

// GetPolicyId returns QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistory.PolicyId, and is useful for accessing the field via an interface.
func (v *QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistory) GetPolicyId() string {
	return v.PolicyId
}

// GetPolicyName returns QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistory.PolicyName, and is useful for accessing the field via an interface.
func (v *QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistory) GetPolicyName() string {
	return v.PolicyName
}

// GetStage returns QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistory.Stage, and is useful for accessing the field via an interface.
func (v *QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistory) GetStage() string {
	return v.Stage
}

// GetArtifact returns QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistory.Artifact, and is useful for accessing the field via an interface.
func (v *QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistory) GetArtifact() string {
	return v.Artifact
}

// GetArtifactTag returns QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistory.ArtifactTag, and is useful for accessing the field via an interface.
func (v *QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistory) GetArtifactTag() string {
	return v.ArtifactTag
}

// GetArtifactSha returns QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistory.ArtifactSha, and is useful for accessing the field via an interface.
func (v *QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistory) GetArtifactSha() string {
	return v.ArtifactSha
}

// GetCreatedAt returns QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistory.CreatedAt, and is useful for accessing the field via an interface.
func (v *QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistory) GetCreatedAt() *time.Time {
	return v.CreatedAt
}

// GetUpdatedAt returns QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistory.UpdatedAt, and is useful for accessing the field via an interface.
func (v *QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistory) GetUpdatedAt() *time.Time {
	return v.UpdatedAt
}

// GetDeployedAt returns QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistory.DeployedAt, and is useful for accessing the field via an interface.
func (v *QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistory) GetDeployedAt() *time.Time {
	return v.DeployedAt
}

// GetHash returns QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistory.Hash, and is useful for accessing the field via an interface.
func (v *QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistory) GetHash() string {
	return v.Hash
}

// GetPass returns QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistory.Pass, and is useful for accessing the field via an interface.
func (v *QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistory) GetPass() *bool {
	return v.Pass
}

// GetMetaData returns QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistory.MetaData, and is useful for accessing the field via an interface.
func (v *QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistory) GetMetaData() string {
	return v.MetaData
}

// GetScheduledPolicy returns QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistory.ScheduledPolicy, and is useful for accessing the field via an interface.
func (v *QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistory) GetScheduledPolicy() *bool {
	return v.ScheduledPolicy
}

// GetDatasourceTool returns QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistory.DatasourceTool, and is useful for accessing the field via an interface.
func (v *QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistory) GetDatasourceTool() string {
	return v.DatasourceTool
}

// GetStatus returns QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistory.Status, and is useful for accessing the field via an interface.
func (v *QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistory) GetStatus() string {
	return v.Status
}

// GetSecurityIssue returns QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistory.SecurityIssue, and is useful for accessing the field via an interface.
func (v *QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistory) GetSecurityIssue() *QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistorySecurityIssue {
	return v.SecurityIssue
}

// GetPolicyEnforcements returns QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistory.PolicyEnforcements, and is useful for accessing the field via an interface.
func (v *QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistory) GetPolicyEnforcements() *QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistoryPolicyEnforcementsPolicyEnforcement {
	return v.PolicyEnforcements
}

// QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistoryPolicyEnforcementsPolicyEnforcement includes the requested fields of the GraphQL type PolicyEnforcement.
type QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistoryPolicyEnforcementsPolicyEnforcement struct {
	Id             *string                                                                                                                          `json:"id"`
	Status         *bool                                                                                                                            `json:"status"`
	Severity       Severity                                                                                                                         `json:"severity"`
	Action         string                                                                                                                           `json:"action"`
	ConditionValue string                                                                                                                           `json:"conditionValue"`
	Policy         *QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistoryPolicyEnforcementsPolicyEnforcementPolicyPolicyDefinition `json:"policy"`
}

// GetId returns QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistoryPolicyEnforcementsPolicyEnforcement.Id, and is useful for accessing the field via an interface.
func (v *QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistoryPolicyEnforcementsPolicyEnforcement) GetId() *string {
	return v.Id
}

// GetStatus returns QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistoryPolicyEnforcementsPolicyEnforcement.Status, and is useful for accessing the field via an interface.
func (v *QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistoryPolicyEnforcementsPolicyEnforcement) GetStatus() *bool {
	return v.Status
}

// GetSeverity returns QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistoryPolicyEnforcementsPolicyEnforcement.Severity, and is useful for accessing the field via an interface.
func (v *QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistoryPolicyEnforcementsPolicyEnforcement) GetSeverity() Severity {
	return v.Severity
}

// GetAction returns QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistoryPolicyEnforcementsPolicyEnforcement.Action, and is useful for accessing the field via an interface.
func (v *QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistoryPolicyEnforcementsPolicyEnforcement) GetAction() string {
	return v.Action
}

// GetConditionValue returns QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistoryPolicyEnforcementsPolicyEnforcement.ConditionValue, and is useful for accessing the field via an interface.
func (v *QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistoryPolicyEnforcementsPolicyEnforcement) GetConditionValue() string {
	return v.ConditionValue
}

// GetPolicy returns QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistoryPolicyEnforcementsPolicyEnforcement.Policy, and is useful for accessing the field via an interface.
func (v *QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistoryPolicyEnforcementsPolicyEnforcement) GetPolicy() *QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistoryPolicyEnforcementsPolicyEnforcementPolicyPolicyDefinition {
	return v.Policy
}

// QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistoryPolicyEnforcementsPolicyEnforcementPolicyPolicyDefinition includes the requested fields of the GraphQL type PolicyDefinition.
type QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistoryPolicyEnforcementsPolicyEnforcementPolicyPolicyDefinition struct {
	Id              string `json:"id"`
	PolicyName      string `json:"policyName"`
	Category        string `json:"category"`
	Stage           string `json:"stage"`
	ScheduledPolicy *bool  `json:"scheduledPolicy"`
	Script          string `json:"script"`
	Variables       string `json:"variables"`
	ConditionName   string `json:"conditionName"`
	Suggestion      string `json:"suggestion"`
}

// GetId returns QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistoryPolicyEnforcementsPolicyEnforcementPolicyPolicyDefinition.Id, and is useful for accessing the field via an interface.
func (v *QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistoryPolicyEnforcementsPolicyEnforcementPolicyPolicyDefinition) GetId() string {
	return v.Id
}

// GetPolicyName returns QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistoryPolicyEnforcementsPolicyEnforcementPolicyPolicyDefinition.PolicyName, and is useful for accessing the field via an interface.
func (v *QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistoryPolicyEnforcementsPolicyEnforcementPolicyPolicyDefinition) GetPolicyName() string {
	return v.PolicyName
}

// GetCategory returns QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistoryPolicyEnforcementsPolicyEnforcementPolicyPolicyDefinition.Category, and is useful for accessing the field via an interface.
func (v *QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistoryPolicyEnforcementsPolicyEnforcementPolicyPolicyDefinition) GetCategory() string {
	return v.Category
}

// GetStage returns QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistoryPolicyEnforcementsPolicyEnforcementPolicyPolicyDefinition.Stage, and is useful for accessing the field via an interface.
func (v *QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistoryPolicyEnforcementsPolicyEnforcementPolicyPolicyDefinition) GetStage() string {
	return v.Stage
}

// GetScheduledPolicy returns QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistoryPolicyEnforcementsPolicyEnforcementPolicyPolicyDefinition.ScheduledPolicy, and is useful for accessing the field via an interface.
func (v *QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistoryPolicyEnforcementsPolicyEnforcementPolicyPolicyDefinition) GetScheduledPolicy() *bool {
	return v.ScheduledPolicy
}

// GetScript returns QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistoryPolicyEnforcementsPolicyEnforcementPolicyPolicyDefinition.Script, and is useful for accessing the field via an interface.
func (v *QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistoryPolicyEnforcementsPolicyEnforcementPolicyPolicyDefinition) GetScript() string {
	return v.Script
}

// GetVariables returns QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistoryPolicyEnforcementsPolicyEnforcementPolicyPolicyDefinition.Variables, and is useful for accessing the field via an interface.
func (v *QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistoryPolicyEnforcementsPolicyEnforcementPolicyPolicyDefinition) GetVariables() string {
	return v.Variables
}

// GetConditionName returns QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistoryPolicyEnforcementsPolicyEnforcementPolicyPolicyDefinition.ConditionName, and is useful for accessing the field via an interface.
func (v *QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistoryPolicyEnforcementsPolicyEnforcementPolicyPolicyDefinition) GetConditionName() string {
	return v.ConditionName
}

// GetSuggestion returns QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistoryPolicyEnforcementsPolicyEnforcementPolicyPolicyDefinition.Suggestion, and is useful for accessing the field via an interface.
func (v *QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistoryPolicyEnforcementsPolicyEnforcementPolicyPolicyDefinition) GetSuggestion() string {
	return v.Suggestion
}

// QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistorySecurityIssue includes the requested fields of the GraphQL type SecurityIssue.
type QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistorySecurityIssue struct {
	AlertTitle   string   `json:"AlertTitle"`
	AlertMessage string   `json:"AlertMessage"`
	Suggestions  string   `json:"Suggestions"`
	Severity     Severity `json:"Severity"`
	Action       string   `json:"Action"`
	Error        string   `json:"Error"`
}

// GetAlertTitle returns QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistorySecurityIssue.AlertTitle, and is useful for accessing the field via an interface.
func (v *QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistorySecurityIssue) GetAlertTitle() string {
	return v.AlertTitle
}

// GetAlertMessage returns QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistorySecurityIssue.AlertMessage, and is useful for accessing the field via an interface.
func (v *QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistorySecurityIssue) GetAlertMessage() string {
	return v.AlertMessage
}

// GetSuggestions returns QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistorySecurityIssue.Suggestions, and is useful for accessing the field via an interface.
func (v *QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistorySecurityIssue) GetSuggestions() string {
	return v.Suggestions
}

// GetSeverity returns QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistorySecurityIssue.Severity, and is useful for accessing the field via an interface.
func (v *QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistorySecurityIssue) GetSeverity() Severity {
	return v.Severity
}

// GetAction returns QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistorySecurityIssue.Action, and is useful for accessing the field via an interface.
func (v *QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistorySecurityIssue) GetAction() string {
	return v.Action
}

// GetError returns QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistorySecurityIssue.Error, and is useful for accessing the field via an interface.
func (v *QueryArtifactScanDataRunHistoryQueryArtifactScanDataArtifactRunHistorySecurityIssue) GetError() string {
	return v.Error
}

// QueryArtifactScanDataRunHistoryResponse is returned by QueryArtifactScanDataRunHistory on success.
type QueryArtifactScanDataRunHistoryResponse struct {
	QueryArtifactScanData []*QueryArtifactScanDataRunHistoryQueryArtifactScanData `json:"queryArtifactScanData"`
}

// GetQueryArtifactScanData returns QueryArtifactScanDataRunHistoryResponse.QueryArtifactScanData, and is useful for accessing the field via an interface.
func (v *QueryArtifactScanDataRunHistoryResponse) GetQueryArtifactScanData() []*QueryArtifactScanDataRunHistoryQueryArtifactScanData {
	return v.QueryArtifactScanData
}

// RiskStatus tells us what risk a current application instance or a deployment is at.
type RiskStatus string

const (
	RiskStatusLowrisk        RiskStatus = "lowrisk"
	RiskStatusMediumrisk     RiskStatus = "mediumrisk"
	RiskStatusHighrisk       RiskStatus = "highrisk"
	RiskStatusApocalypserisk RiskStatus = "apocalypserisk"
	RiskStatusScanning       RiskStatus = "scanning"
)

type Severity string

const (
	SeverityCritical Severity = "critical"
	SeverityHigh     Severity = "high"
	SeverityMedium   Severity = "medium"
	SeverityLow      Severity = "low"
	SeverityInfo     Severity = "info"
	SeverityNone     Severity = "none"
	SeverityUnknown  Severity = "unknown"
)

// UpdateArtifactScanDataResponse is returned by UpdateArtifactScanData on success.
type UpdateArtifactScanDataResponse struct {
	UpdateArtifactScanData *UpdateArtifactScanDataUpdateArtifactScanDataUpdateArtifactScanDataPayload `json:"updateArtifactScanData"`
}

// GetUpdateArtifactScanData returns UpdateArtifactScanDataResponse.UpdateArtifactScanData, and is useful for accessing the field via an interface.
func (v *UpdateArtifactScanDataResponse) GetUpdateArtifactScanData() *UpdateArtifactScanDataUpdateArtifactScanDataUpdateArtifactScanDataPayload {
	return v.UpdateArtifactScanData
}

// UpdateArtifactScanDataRiskScoreAndStatusResponse is returned by UpdateArtifactScanDataRiskScoreAndStatus on success.
type UpdateArtifactScanDataRiskScoreAndStatusResponse struct {
	UpdateArtifactRisk *UpdateArtifactScanDataRiskScoreAndStatusUpdateArtifactRiskUpdateArtifactRiskPayload `json:"updateArtifactRisk"`
}

// GetUpdateArtifactRisk returns UpdateArtifactScanDataRiskScoreAndStatusResponse.UpdateArtifactRisk, and is useful for accessing the field via an interface.
func (v *UpdateArtifactScanDataRiskScoreAndStatusResponse) GetUpdateArtifactRisk() *UpdateArtifactScanDataRiskScoreAndStatusUpdateArtifactRiskUpdateArtifactRiskPayload {
	return v.UpdateArtifactRisk
}

// UpdateArtifactScanDataRiskScoreAndStatusUpdateArtifactRiskUpdateArtifactRiskPayload includes the requested fields of the GraphQL type UpdateArtifactRiskPayload.
type UpdateArtifactScanDataRiskScoreAndStatusUpdateArtifactRiskUpdateArtifactRiskPayload struct {
	NumUids *int `json:"numUids"`
}

// GetNumUids returns UpdateArtifactScanDataRiskScoreAndStatusUpdateArtifactRiskUpdateArtifactRiskPayload.NumUids, and is useful for accessing the field via an interface.
func (v *UpdateArtifactScanDataRiskScoreAndStatusUpdateArtifactRiskUpdateArtifactRiskPayload) GetNumUids() *int {
	return v.NumUids
}

// UpdateArtifactScanDataUpdateArtifactScanDataUpdateArtifactScanDataPayload includes the requested fields of the GraphQL type UpdateArtifactScanDataPayload.
type UpdateArtifactScanDataUpdateArtifactScanDataUpdateArtifactScanDataPayload struct {
	ArtifactScanData []*UpdateArtifactScanDataUpdateArtifactScanDataUpdateArtifactScanDataPayloadArtifactScanData `json:"artifactScanData"`
}

// GetArtifactScanData returns UpdateArtifactScanDataUpdateArtifactScanDataUpdateArtifactScanDataPayload.ArtifactScanData, and is useful for accessing the field via an interface.
func (v *UpdateArtifactScanDataUpdateArtifactScanDataUpdateArtifactScanDataPayload) GetArtifactScanData() []*UpdateArtifactScanDataUpdateArtifactScanDataUpdateArtifactScanDataPayloadArtifactScanData {
	return v.ArtifactScanData
}

// UpdateArtifactScanDataUpdateArtifactScanDataUpdateArtifactScanDataPayloadArtifactScanData includes the requested fields of the GraphQL type ArtifactScanData.
type UpdateArtifactScanDataUpdateArtifactScanDataUpdateArtifactScanDataPayloadArtifactScanData struct {
	ArtifactRisk *UpdateArtifactScanDataUpdateArtifactScanDataUpdateArtifactScanDataPayloadArtifactScanDataArtifactRisk `json:"artifactRisk"`
}

// GetArtifactRisk returns UpdateArtifactScanDataUpdateArtifactScanDataUpdateArtifactScanDataPayloadArtifactScanData.ArtifactRisk, and is useful for accessing the field via an interface.
func (v *UpdateArtifactScanDataUpdateArtifactScanDataUpdateArtifactScanDataPayloadArtifactScanData) GetArtifactRisk() *UpdateArtifactScanDataUpdateArtifactScanDataUpdateArtifactScanDataPayloadArtifactScanDataArtifactRisk {
	return v.ArtifactRisk
}

// UpdateArtifactScanDataUpdateArtifactScanDataUpdateArtifactScanDataPayloadArtifactScanDataArtifactRisk includes the requested fields of the GraphQL type ArtifactRisk.
type UpdateArtifactScanDataUpdateArtifactScanDataUpdateArtifactScanDataPayloadArtifactScanDataArtifactRisk struct {
	Id *string `json:"id"`
}

// GetId returns UpdateArtifactScanDataUpdateArtifactScanDataUpdateArtifactScanDataPayloadArtifactScanDataArtifactRisk.Id, and is useful for accessing the field via an interface.
func (v *UpdateArtifactScanDataUpdateArtifactScanDataUpdateArtifactScanDataPayloadArtifactScanDataArtifactRisk) GetId() *string {
	return v.Id
}

// __DeleteArtifactScanDataInput is used internally by genqlient
type __DeleteArtifactScanDataInput struct {
	Id string `json:"id"`
}

// GetId returns __DeleteArtifactScanDataInput.Id, and is useful for accessing the field via an interface.
func (v *__DeleteArtifactScanDataInput) GetId() string { return v.Id }

// __GetArtifactRiskInput is used internally by genqlient
type __GetArtifactRiskInput struct {
	Id *string `json:"id"`
}

// GetId returns __GetArtifactRiskInput.Id, and is useful for accessing the field via an interface.
func (v *__GetArtifactRiskInput) GetId() *string { return v.Id }

// __QueryArtifactScanDataRunHistoryInput is used internally by genqlient
type __QueryArtifactScanDataRunHistoryInput struct {
	ScanDataId string `json:"scanDataId"`
}

// GetScanDataId returns __QueryArtifactScanDataRunHistoryInput.ScanDataId, and is useful for accessing the field via an interface.
func (v *__QueryArtifactScanDataRunHistoryInput) GetScanDataId() string { return v.ScanDataId }

// __UpdateArtifactScanDataInput is used internally by genqlient
type __UpdateArtifactScanDataInput struct {
	ArtifactScanDataId string `json:"artifactScanDataId"`
}

// GetArtifactScanDataId returns __UpdateArtifactScanDataInput.ArtifactScanDataId, and is useful for accessing the field via an interface.
func (v *__UpdateArtifactScanDataInput) GetArtifactScanDataId() string { return v.ArtifactScanDataId }

// __UpdateArtifactScanDataRiskScoreAndStatusInput is used internally by genqlient
type __UpdateArtifactScanDataRiskScoreAndStatusInput struct {
	Id                    *string    `json:"id"`
	RiskStatus            RiskStatus `json:"riskStatus"`
	BuildAlertsScore      *int       `json:"buildAlertsScore"`
	SourceCodeAlertsScore *int       `json:"sourceCodeAlertsScore"`
	ArtifactAlertsScore   *int       `json:"artifactAlertsScore"`
	DeploymentAlertsScore *int       `json:"deploymentAlertsScore"`
}

// GetId returns __UpdateArtifactScanDataRiskScoreAndStatusInput.Id, and is useful for accessing the field via an interface.
func (v *__UpdateArtifactScanDataRiskScoreAndStatusInput) GetId() *string { return v.Id }

// GetRiskStatus returns __UpdateArtifactScanDataRiskScoreAndStatusInput.RiskStatus, and is useful for accessing the field via an interface.
func (v *__UpdateArtifactScanDataRiskScoreAndStatusInput) GetRiskStatus() RiskStatus {
	return v.RiskStatus
}

// GetBuildAlertsScore returns __UpdateArtifactScanDataRiskScoreAndStatusInput.BuildAlertsScore, and is useful for accessing the field via an interface.
func (v *__UpdateArtifactScanDataRiskScoreAndStatusInput) GetBuildAlertsScore() *int {
	return v.BuildAlertsScore
}

// GetSourceCodeAlertsScore returns __UpdateArtifactScanDataRiskScoreAndStatusInput.SourceCodeAlertsScore, and is useful for accessing the field via an interface.
func (v *__UpdateArtifactScanDataRiskScoreAndStatusInput) GetSourceCodeAlertsScore() *int {
	return v.SourceCodeAlertsScore
}

// GetArtifactAlertsScore returns __UpdateArtifactScanDataRiskScoreAndStatusInput.ArtifactAlertsScore, and is useful for accessing the field via an interface.
func (v *__UpdateArtifactScanDataRiskScoreAndStatusInput) GetArtifactAlertsScore() *int {
	return v.ArtifactAlertsScore
}

// GetDeploymentAlertsScore returns __UpdateArtifactScanDataRiskScoreAndStatusInput.DeploymentAlertsScore, and is useful for accessing the field via an interface.
func (v *__UpdateArtifactScanDataRiskScoreAndStatusInput) GetDeploymentAlertsScore() *int {
	return v.DeploymentAlertsScore
}

// The query or mutation executed by DeleteArtifactScanData.
const DeleteArtifactScanData_Operation = `
mutation DeleteArtifactScanData ($id: String) {
	deleteArtifactScanData(filter: {id:{eq:$id}}) {
		msg
		numUids
	}
}
`

func DeleteArtifactScanData(
	ctx_ context.Context,
	client_ graphql.Client,
	id string,
) (*DeleteArtifactScanDataResponse, error) {
	req_ := &graphql.Request{
		OpName: "DeleteArtifactScanData",
		Query:  DeleteArtifactScanData_Operation,
		Variables: &__DeleteArtifactScanDataInput{
			Id: id,
		},
	}
	var err_ error

	var data_ DeleteArtifactScanDataResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}

// The query or mutation executed by DeleteArtifactScanDataForInprogress.
const DeleteArtifactScanDataForInprogress_Operation = `
mutation DeleteArtifactScanDataForInprogress {
	deleteArtifactScanData(filter: {vulnScanState:{eq:"inprogress"}}) {
		numUids
	}
}
`

func DeleteArtifactScanDataForInprogress(
	ctx_ context.Context,
	client_ graphql.Client,
) (*DeleteArtifactScanDataForInprogressResponse, error) {
	req_ := &graphql.Request{
		OpName: "DeleteArtifactScanDataForInprogress",
		Query:  DeleteArtifactScanDataForInprogress_Operation,
	}
	var err_ error

	var data_ DeleteArtifactScanDataForInprogressResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}

// The query or mutation executed by DeleteArtifactScanDataNotHaveArtifact.
const DeleteArtifactScanDataNotHaveArtifact_Operation = `
mutation DeleteArtifactScanDataNotHaveArtifact {
	deleteArtifactScanData(filter: {not:{has:artifactDetails}}) {
		numUids
	}
}
`

func DeleteArtifactScanDataNotHaveArtifact(
	ctx_ context.Context,
	client_ graphql.Client,
) (*DeleteArtifactScanDataNotHaveArtifactResponse, error) {
	req_ := &graphql.Request{
		OpName: "DeleteArtifactScanDataNotHaveArtifact",
		Query:  DeleteArtifactScanDataNotHaveArtifact_Operation,
	}
	var err_ error

	var data_ DeleteArtifactScanDataNotHaveArtifactResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}

// The query or mutation executed by GetArtifactRisk.
const GetArtifactRisk_Operation = `
query GetArtifactRisk ($id: ID!) {
	getArtifactRisk(id: $id) {
		sourceCodeAlertsScore
		buildAlertsScore
		artifactAlertsScore
		deploymentAlertsScore
		artifactRiskStatus
	}
}
`

func GetArtifactRisk(
	ctx_ context.Context,
	client_ graphql.Client,
	id *string,
) (*GetArtifactRiskResponse, error) {
	req_ := &graphql.Request{
		OpName: "GetArtifactRisk",
		Query:  GetArtifactRisk_Operation,
		Variables: &__GetArtifactRiskInput{
			Id: id,
		},
	}
	var err_ error

	var data_ GetArtifactRiskResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}

// The query or mutation executed by GetArtifactScanDataId.
const GetArtifactScanDataId_Operation = `
query GetArtifactScanDataId {
	queryArtifactScanData {
		id
		artifactRisk {
			id
		}
	}
}
`

func GetArtifactScanDataId(
	ctx_ context.Context,
	client_ graphql.Client,
) (*GetArtifactScanDataIdResponse, error) {
	req_ := &graphql.Request{
		OpName: "GetArtifactScanDataId",
		Query:  GetArtifactScanDataId_Operation,
	}
	var err_ error

	var data_ GetArtifactScanDataIdResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}

// The query or mutation executed by QueryArtifactScanDataRunHistory.
const QueryArtifactScanDataRunHistory_Operation = `
query QueryArtifactScanDataRunHistory ($scanDataId: String!) {
	queryArtifactScanData(filter: {id:{eq:$scanDataId}}) @cascade(fields: ["artifactRunHistory"]) {
		artifactRunHistory @cascade(fields: ["id"]) {
			id
			policyId
			PolicyName
			Stage
			Artifact
			ArtifactTag
			ArtifactSha
			CreatedAt
			UpdatedAt
			DeployedAt
			Hash
			Pass
			MetaData
			scheduledPolicy
			DatasourceTool
			Status
			securityIssue {
				AlertTitle
				AlertMessage
				Suggestions
				Severity
				Action
				Error
			}
			policyEnforcements {
				id
				status
				severity
				action
				conditionValue
				policy {
					id
					policyName
					category
					stage
					scheduledPolicy
					script
					variables
					conditionName
					suggestion
				}
			}
		}
	}
}
`

func QueryArtifactScanDataRunHistory(
	ctx_ context.Context,
	client_ graphql.Client,
	scanDataId string,
) (*QueryArtifactScanDataRunHistoryResponse, error) {
	req_ := &graphql.Request{
		OpName: "QueryArtifactScanDataRunHistory",
		Query:  QueryArtifactScanDataRunHistory_Operation,
		Variables: &__QueryArtifactScanDataRunHistoryInput{
			ScanDataId: scanDataId,
		},
	}
	var err_ error

	var data_ QueryArtifactScanDataRunHistoryResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}

// The query or mutation executed by UpdateArtifactScanData.
const UpdateArtifactScanData_Operation = `
mutation UpdateArtifactScanData ($artifactScanDataId: String!) {
	updateArtifactScanData(input: {set:{artifactRisk:{artifactRiskStatus:scanning}},filter:{id:{eq:$artifactScanDataId}}}) {
		artifactScanData {
			artifactRisk {
				id
			}
		}
	}
}
`

func UpdateArtifactScanData(
	ctx_ context.Context,
	client_ graphql.Client,
	artifactScanDataId string,
) (*UpdateArtifactScanDataResponse, error) {
	req_ := &graphql.Request{
		OpName: "UpdateArtifactScanData",
		Query:  UpdateArtifactScanData_Operation,
		Variables: &__UpdateArtifactScanDataInput{
			ArtifactScanDataId: artifactScanDataId,
		},
	}
	var err_ error

	var data_ UpdateArtifactScanDataResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}

// The query or mutation executed by UpdateArtifactScanDataRiskScoreAndStatus.
const UpdateArtifactScanDataRiskScoreAndStatus_Operation = `
mutation UpdateArtifactScanDataRiskScoreAndStatus ($id: ID!, $riskStatus: RiskStatus!, $buildAlertsScore: Int, $sourceCodeAlertsScore: Int, $artifactAlertsScore: Int, $deploymentAlertsScore: Int) {
	updateArtifactRisk(input: {set:{artifactRiskStatus:$riskStatus,sourceCodeAlertsScore:$sourceCodeAlertsScore,buildAlertsScore:$buildAlertsScore,artifactAlertsScore:$artifactAlertsScore,deploymentAlertsScore:$deploymentAlertsScore},filter:{id:[$id]}}) {
		numUids
	}
}
`

func UpdateArtifactScanDataRiskScoreAndStatus(
	ctx_ context.Context,
	client_ graphql.Client,
	id *string,
	riskStatus RiskStatus,
	buildAlertsScore *int,
	sourceCodeAlertsScore *int,
	artifactAlertsScore *int,
	deploymentAlertsScore *int,
) (*UpdateArtifactScanDataRiskScoreAndStatusResponse, error) {
	req_ := &graphql.Request{
		OpName: "UpdateArtifactScanDataRiskScoreAndStatus",
		Query:  UpdateArtifactScanDataRiskScoreAndStatus_Operation,
		Variables: &__UpdateArtifactScanDataRiskScoreAndStatusInput{
			Id:                    id,
			RiskStatus:            riskStatus,
			BuildAlertsScore:      buildAlertsScore,
			SourceCodeAlertsScore: sourceCodeAlertsScore,
			ArtifactAlertsScore:   artifactAlertsScore,
			DeploymentAlertsScore: deploymentAlertsScore,
		},
	}
	var err_ error

	var data_ UpdateArtifactScanDataRiskScoreAndStatusResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}
