// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package july2024

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

type ScanFileResultRef struct {
	Id   *string `json:"id"`
	Name string  `json:"name"`
	Url  string  `json:"url"`
}

// GetId returns ScanFileResultRef.Id, and is useful for accessing the field via an interface.
func (v *ScanFileResultRef) GetId() *string { return v.Id }

// GetName returns ScanFileResultRef.Name, and is useful for accessing the field via an interface.
func (v *ScanFileResultRef) GetName() string { return v.Name }

// GetUrl returns ScanFileResultRef.Url, and is useful for accessing the field via an interface.
func (v *ScanFileResultRef) GetUrl() string { return v.Url }

// UpdateScannedFilesInArtifactScanDataResponse is returned by UpdateScannedFilesInArtifactScanData on success.
type UpdateScannedFilesInArtifactScanDataResponse struct {
	UpdateArtifactScanData *UpdateScannedFilesInArtifactScanDataUpdateArtifactScanDataUpdateArtifactScanDataPayload `json:"updateArtifactScanData"`
}

// GetUpdateArtifactScanData returns UpdateScannedFilesInArtifactScanDataResponse.UpdateArtifactScanData, and is useful for accessing the field via an interface.
func (v *UpdateScannedFilesInArtifactScanDataResponse) GetUpdateArtifactScanData() *UpdateScannedFilesInArtifactScanDataUpdateArtifactScanDataUpdateArtifactScanDataPayload {
	return v.UpdateArtifactScanData
}

// UpdateScannedFilesInArtifactScanDataUpdateArtifactScanDataUpdateArtifactScanDataPayload includes the requested fields of the GraphQL type UpdateArtifactScanDataPayload.
type UpdateScannedFilesInArtifactScanDataUpdateArtifactScanDataUpdateArtifactScanDataPayload struct {
	NumUids *int `json:"numUids"`
}

// GetNumUids returns UpdateScannedFilesInArtifactScanDataUpdateArtifactScanDataUpdateArtifactScanDataPayload.NumUids, and is useful for accessing the field via an interface.
func (v *UpdateScannedFilesInArtifactScanDataUpdateArtifactScanDataUpdateArtifactScanDataPayload) GetNumUids() *int {
	return v.NumUids
}

// __UpdateScannedFilesInArtifactScanDataInput is used internally by genqlient
type __UpdateScannedFilesInArtifactScanDataInput struct {
	Files []*ScanFileResultRef `json:"files,omitempty"`
	Id    string               `json:"id"`
}

// GetFiles returns __UpdateScannedFilesInArtifactScanDataInput.Files, and is useful for accessing the field via an interface.
func (v *__UpdateScannedFilesInArtifactScanDataInput) GetFiles() []*ScanFileResultRef { return v.Files }

// GetId returns __UpdateScannedFilesInArtifactScanDataInput.Id, and is useful for accessing the field via an interface.
func (v *__UpdateScannedFilesInArtifactScanDataInput) GetId() string { return v.Id }

// The query or mutation executed by UpdateScannedFilesInArtifactScanData.
const UpdateScannedFilesInArtifactScanData_Operation = `
mutation UpdateScannedFilesInArtifactScanData ($files: [ScanFileResultRef!], $id: String!) {
	updateArtifactScanData(input: {set:{scanFile:$files},filter:{id:{eq:$id}}}) {
		numUids
	}
}
`

func UpdateScannedFilesInArtifactScanData(
	ctx_ context.Context,
	client_ graphql.Client,
	files []*ScanFileResultRef,
	id string,
) (*UpdateScannedFilesInArtifactScanDataResponse, error) {
	req_ := &graphql.Request{
		OpName: "UpdateScannedFilesInArtifactScanData",
		Query:  UpdateScannedFilesInArtifactScanData_Operation,
		Variables: &__UpdateScannedFilesInArtifactScanDataInput{
			Files: files,
			Id:    id,
		},
	}
	var err_ error

	var data_ UpdateScannedFilesInArtifactScanDataResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}
