// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package february2025march2025

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

// QueryRunHistoryWithApplicationDeploymentQueryRunHistory includes the requested fields of the GraphQL type RunHistory.
type QueryRunHistoryWithApplicationDeploymentQueryRunHistory struct {
	Id                    *string                                                                       `json:"id"`
	ApplicationDeployment *QueryRunHistoryWithApplicationDeploymentQueryRunHistoryApplicationDeployment `json:"applicationDeployment"`
}

// GetId returns QueryRunHistoryWithApplicationDeploymentQueryRunHistory.Id, and is useful for accessing the field via an interface.
func (v *QueryRunHistoryWithApplicationDeploymentQueryRunHistory) GetId() *string { return v.Id }

// GetApplicationDeployment returns QueryRunHistoryWithApplicationDeploymentQueryRunHistory.ApplicationDeployment, and is useful for accessing the field via an interface.
func (v *QueryRunHistoryWithApplicationDeploymentQueryRunHistory) GetApplicationDeployment() *QueryRunHistoryWithApplicationDeploymentQueryRunHistoryApplicationDeployment {
	return v.ApplicationDeployment
}

// QueryRunHistoryWithApplicationDeploymentQueryRunHistoryApplicationDeployment includes the requested fields of the GraphQL type ApplicationDeployment.
// The GraphQL type's documentation follows.
//
// ApplicationDeployment tells us about the the artifact deployed along with its associated details.
type QueryRunHistoryWithApplicationDeploymentQueryRunHistoryApplicationDeployment struct {
	ApplicationEnvironment *QueryRunHistoryWithApplicationDeploymentQueryRunHistoryApplicationDeploymentApplicationEnvironment `json:"applicationEnvironment"`
	// toolsUsed contains tools of different stages of source, build, artifact and deploy along with some different tools
	ToolsUsed *QueryRunHistoryWithApplicationDeploymentQueryRunHistoryApplicationDeploymentToolsUsed `json:"toolsUsed"`
	// id is randomly assigned
	Id string `json:"id"`
}

// GetApplicationEnvironment returns QueryRunHistoryWithApplicationDeploymentQueryRunHistoryApplicationDeployment.ApplicationEnvironment, and is useful for accessing the field via an interface.
func (v *QueryRunHistoryWithApplicationDeploymentQueryRunHistoryApplicationDeployment) GetApplicationEnvironment() *QueryRunHistoryWithApplicationDeploymentQueryRunHistoryApplicationDeploymentApplicationEnvironment {
	return v.ApplicationEnvironment
}

// GetToolsUsed returns QueryRunHistoryWithApplicationDeploymentQueryRunHistoryApplicationDeployment.ToolsUsed, and is useful for accessing the field via an interface.
func (v *QueryRunHistoryWithApplicationDeploymentQueryRunHistoryApplicationDeployment) GetToolsUsed() *QueryRunHistoryWithApplicationDeploymentQueryRunHistoryApplicationDeploymentToolsUsed {
	return v.ToolsUsed
}

// GetId returns QueryRunHistoryWithApplicationDeploymentQueryRunHistoryApplicationDeployment.Id, and is useful for accessing the field via an interface.
func (v *QueryRunHistoryWithApplicationDeploymentQueryRunHistoryApplicationDeployment) GetId() string {
	return v.Id
}

// QueryRunHistoryWithApplicationDeploymentQueryRunHistoryApplicationDeploymentApplicationEnvironment includes the requested fields of the GraphQL type ApplicationEnvironment.
// The GraphQL type's documentation follows.
//
// ApplicationEnvironment is a running instance of an application down to the level of a namespace or its non k8s equivalent.
type QueryRunHistoryWithApplicationDeploymentQueryRunHistoryApplicationDeploymentApplicationEnvironment struct {
	Namespace        string                                                                                                              `json:"namespace"`
	Application      *QueryRunHistoryWithApplicationDeploymentQueryRunHistoryApplicationDeploymentApplicationEnvironmentApplication      `json:"application"`
	DeploymentTarget *QueryRunHistoryWithApplicationDeploymentQueryRunHistoryApplicationDeploymentApplicationEnvironmentDeploymentTarget `json:"deploymentTarget"`
	// environment denotes whether it is dev, prod, staging, non-prod etc
	Environment *QueryRunHistoryWithApplicationDeploymentQueryRunHistoryApplicationDeploymentApplicationEnvironmentEnvironment `json:"environment"`
}

// GetNamespace returns QueryRunHistoryWithApplicationDeploymentQueryRunHistoryApplicationDeploymentApplicationEnvironment.Namespace, and is useful for accessing the field via an interface.
func (v *QueryRunHistoryWithApplicationDeploymentQueryRunHistoryApplicationDeploymentApplicationEnvironment) GetNamespace() string {
	return v.Namespace
}

// GetApplication returns QueryRunHistoryWithApplicationDeploymentQueryRunHistoryApplicationDeploymentApplicationEnvironment.Application, and is useful for accessing the field via an interface.
func (v *QueryRunHistoryWithApplicationDeploymentQueryRunHistoryApplicationDeploymentApplicationEnvironment) GetApplication() *QueryRunHistoryWithApplicationDeploymentQueryRunHistoryApplicationDeploymentApplicationEnvironmentApplication {
	return v.Application
}

// GetDeploymentTarget returns QueryRunHistoryWithApplicationDeploymentQueryRunHistoryApplicationDeploymentApplicationEnvironment.DeploymentTarget, and is useful for accessing the field via an interface.
func (v *QueryRunHistoryWithApplicationDeploymentQueryRunHistoryApplicationDeploymentApplicationEnvironment) GetDeploymentTarget() *QueryRunHistoryWithApplicationDeploymentQueryRunHistoryApplicationDeploymentApplicationEnvironmentDeploymentTarget {
	return v.DeploymentTarget
}

// GetEnvironment returns QueryRunHistoryWithApplicationDeploymentQueryRunHistoryApplicationDeploymentApplicationEnvironment.Environment, and is useful for accessing the field via an interface.
func (v *QueryRunHistoryWithApplicationDeploymentQueryRunHistoryApplicationDeploymentApplicationEnvironment) GetEnvironment() *QueryRunHistoryWithApplicationDeploymentQueryRunHistoryApplicationDeploymentApplicationEnvironmentEnvironment {
	return v.Environment
}

// QueryRunHistoryWithApplicationDeploymentQueryRunHistoryApplicationDeploymentApplicationEnvironmentApplication includes the requested fields of the GraphQL type Application.
type QueryRunHistoryWithApplicationDeploymentQueryRunHistoryApplicationDeploymentApplicationEnvironmentApplication struct {
	Team *QueryRunHistoryWithApplicationDeploymentQueryRunHistoryApplicationDeploymentApplicationEnvironmentApplicationTeam `json:"team"`
	Name string                                                                                                             `json:"name"`
}

// GetTeam returns QueryRunHistoryWithApplicationDeploymentQueryRunHistoryApplicationDeploymentApplicationEnvironmentApplication.Team, and is useful for accessing the field via an interface.
func (v *QueryRunHistoryWithApplicationDeploymentQueryRunHistoryApplicationDeploymentApplicationEnvironmentApplication) GetTeam() *QueryRunHistoryWithApplicationDeploymentQueryRunHistoryApplicationDeploymentApplicationEnvironmentApplicationTeam {
	return v.Team
}

// GetName returns QueryRunHistoryWithApplicationDeploymentQueryRunHistoryApplicationDeploymentApplicationEnvironmentApplication.Name, and is useful for accessing the field via an interface.
func (v *QueryRunHistoryWithApplicationDeploymentQueryRunHistoryApplicationDeploymentApplicationEnvironmentApplication) GetName() string {
	return v.Name
}

// QueryRunHistoryWithApplicationDeploymentQueryRunHistoryApplicationDeploymentApplicationEnvironmentApplicationTeam includes the requested fields of the GraphQL type Team.
type QueryRunHistoryWithApplicationDeploymentQueryRunHistoryApplicationDeploymentApplicationEnvironmentApplicationTeam struct {
	// id is randomly assigned
	Id string `json:"id"`
}

// GetId returns QueryRunHistoryWithApplicationDeploymentQueryRunHistoryApplicationDeploymentApplicationEnvironmentApplicationTeam.Id, and is useful for accessing the field via an interface.
func (v *QueryRunHistoryWithApplicationDeploymentQueryRunHistoryApplicationDeploymentApplicationEnvironmentApplicationTeam) GetId() string {
	return v.Id
}

// QueryRunHistoryWithApplicationDeploymentQueryRunHistoryApplicationDeploymentApplicationEnvironmentDeploymentTarget includes the requested fields of the GraphQL type DeploymentTarget.
// The GraphQL type's documentation follows.
//
// DeploymentTarget describes a single place that things can be deployed into,
// such as an AWS account or a Kubernetes cluster.
type QueryRunHistoryWithApplicationDeploymentQueryRunHistoryApplicationDeploymentApplicationEnvironmentDeploymentTarget struct {
	Name string `json:"name"`
}

// GetName returns QueryRunHistoryWithApplicationDeploymentQueryRunHistoryApplicationDeploymentApplicationEnvironmentDeploymentTarget.Name, and is useful for accessing the field via an interface.
func (v *QueryRunHistoryWithApplicationDeploymentQueryRunHistoryApplicationDeploymentApplicationEnvironmentDeploymentTarget) GetName() string {
	return v.Name
}

// QueryRunHistoryWithApplicationDeploymentQueryRunHistoryApplicationDeploymentApplicationEnvironmentEnvironment includes the requested fields of the GraphQL type Environment.
// The GraphQL type's documentation follows.
//
// Environment can be things like dev, prod, staging etc.
type QueryRunHistoryWithApplicationDeploymentQueryRunHistoryApplicationDeploymentApplicationEnvironmentEnvironment struct {
	Purpose string `json:"purpose"`
}

// GetPurpose returns QueryRunHistoryWithApplicationDeploymentQueryRunHistoryApplicationDeploymentApplicationEnvironmentEnvironment.Purpose, and is useful for accessing the field via an interface.
func (v *QueryRunHistoryWithApplicationDeploymentQueryRunHistoryApplicationDeploymentApplicationEnvironmentEnvironment) GetPurpose() string {
	return v.Purpose
}

// QueryRunHistoryWithApplicationDeploymentQueryRunHistoryApplicationDeploymentToolsUsed includes the requested fields of the GraphQL type ToolsUsed.
type QueryRunHistoryWithApplicationDeploymentQueryRunHistoryApplicationDeploymentToolsUsed struct {
	Sbom string `json:"sbom"`
}

// GetSbom returns QueryRunHistoryWithApplicationDeploymentQueryRunHistoryApplicationDeploymentToolsUsed.Sbom, and is useful for accessing the field via an interface.
func (v *QueryRunHistoryWithApplicationDeploymentQueryRunHistoryApplicationDeploymentToolsUsed) GetSbom() string {
	return v.Sbom
}

// QueryRunHistoryWithApplicationDeploymentResponse is returned by QueryRunHistoryWithApplicationDeployment on success.
type QueryRunHistoryWithApplicationDeploymentResponse struct {
	QueryRunHistory []*QueryRunHistoryWithApplicationDeploymentQueryRunHistory `json:"queryRunHistory"`
}

// GetQueryRunHistory returns QueryRunHistoryWithApplicationDeploymentResponse.QueryRunHistory, and is useful for accessing the field via an interface.
func (v *QueryRunHistoryWithApplicationDeploymentResponse) GetQueryRunHistory() []*QueryRunHistoryWithApplicationDeploymentQueryRunHistory {
	return v.QueryRunHistory
}

// UpdateRunHistoryDeploymentFieldsResponse is returned by UpdateRunHistoryDeploymentFields on success.
type UpdateRunHistoryDeploymentFieldsResponse struct {
	UpdateRunHistory *UpdateRunHistoryDeploymentFieldsUpdateRunHistoryUpdateRunHistoryPayload `json:"updateRunHistory"`
}

// GetUpdateRunHistory returns UpdateRunHistoryDeploymentFieldsResponse.UpdateRunHistory, and is useful for accessing the field via an interface.
func (v *UpdateRunHistoryDeploymentFieldsResponse) GetUpdateRunHistory() *UpdateRunHistoryDeploymentFieldsUpdateRunHistoryUpdateRunHistoryPayload {
	return v.UpdateRunHistory
}

// UpdateRunHistoryDeploymentFieldsUpdateRunHistoryUpdateRunHistoryPayload includes the requested fields of the GraphQL type UpdateRunHistoryPayload.
type UpdateRunHistoryDeploymentFieldsUpdateRunHistoryUpdateRunHistoryPayload struct {
	NumUids *int `json:"numUids"`
}

// GetNumUids returns UpdateRunHistoryDeploymentFieldsUpdateRunHistoryUpdateRunHistoryPayload.NumUids, and is useful for accessing the field via an interface.
func (v *UpdateRunHistoryDeploymentFieldsUpdateRunHistoryUpdateRunHistoryPayload) GetNumUids() *int {
	return v.NumUids
}

// __UpdateRunHistoryDeploymentFieldsInput is used internally by genqlient
type __UpdateRunHistoryDeploymentFieldsInput struct {
	RunHistoryID *string `json:"runHistoryID"`
	DeploymentID string  `json:"deploymentID"`
	SbomTool     string  `json:"sbomTool"`
	Namespace    string  `json:"namespace"`
	Account      string  `json:"account"`
	Cluster      string  `json:"cluster"`
	Application  string  `json:"application"`
	TeamID       string  `json:"teamID"`
}

// GetRunHistoryID returns __UpdateRunHistoryDeploymentFieldsInput.RunHistoryID, and is useful for accessing the field via an interface.
func (v *__UpdateRunHistoryDeploymentFieldsInput) GetRunHistoryID() *string { return v.RunHistoryID }

// GetDeploymentID returns __UpdateRunHistoryDeploymentFieldsInput.DeploymentID, and is useful for accessing the field via an interface.
func (v *__UpdateRunHistoryDeploymentFieldsInput) GetDeploymentID() string { return v.DeploymentID }

// GetSbomTool returns __UpdateRunHistoryDeploymentFieldsInput.SbomTool, and is useful for accessing the field via an interface.
func (v *__UpdateRunHistoryDeploymentFieldsInput) GetSbomTool() string { return v.SbomTool }

// GetNamespace returns __UpdateRunHistoryDeploymentFieldsInput.Namespace, and is useful for accessing the field via an interface.
func (v *__UpdateRunHistoryDeploymentFieldsInput) GetNamespace() string { return v.Namespace }

// GetAccount returns __UpdateRunHistoryDeploymentFieldsInput.Account, and is useful for accessing the field via an interface.
func (v *__UpdateRunHistoryDeploymentFieldsInput) GetAccount() string { return v.Account }

// GetCluster returns __UpdateRunHistoryDeploymentFieldsInput.Cluster, and is useful for accessing the field via an interface.
func (v *__UpdateRunHistoryDeploymentFieldsInput) GetCluster() string { return v.Cluster }

// GetApplication returns __UpdateRunHistoryDeploymentFieldsInput.Application, and is useful for accessing the field via an interface.
func (v *__UpdateRunHistoryDeploymentFieldsInput) GetApplication() string { return v.Application }

// GetTeamID returns __UpdateRunHistoryDeploymentFieldsInput.TeamID, and is useful for accessing the field via an interface.
func (v *__UpdateRunHistoryDeploymentFieldsInput) GetTeamID() string { return v.TeamID }

// The query executed by QueryRunHistoryWithApplicationDeployment.
const QueryRunHistoryWithApplicationDeployment_Operation = `
query QueryRunHistoryWithApplicationDeployment {
	queryRunHistory @cascade {
		id
		applicationDeployment {
			applicationEnvironment {
				namespace
				application {
					team {
						id
					}
					name
				}
				deploymentTarget {
					name
				}
				environment {
					purpose
				}
			}
			toolsUsed {
				sbom
			}
			id
		}
	}
}
`

func QueryRunHistoryWithApplicationDeployment(
	ctx_ context.Context,
	client_ graphql.Client,
) (data_ *QueryRunHistoryWithApplicationDeploymentResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "QueryRunHistoryWithApplicationDeployment",
		Query:  QueryRunHistoryWithApplicationDeployment_Operation,
	}

	data_ = &QueryRunHistoryWithApplicationDeploymentResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by UpdateRunHistoryDeploymentFields.
const UpdateRunHistoryDeploymentFields_Operation = `
mutation UpdateRunHistoryDeploymentFields ($runHistoryID: ID!, $deploymentID: String!, $sbomTool: String!, $namespace: String!, $account: String!, $cluster: String!, $application: String!, $teamID: String!) {
	updateRunHistory(input: {filter:{id:[$runHistoryID]},set:{DeploymentID:$deploymentID,SbomTool:$sbomTool,Namespace:$namespace,Account:$account,Cluster:$cluster,Application:$application,TeamID:$teamID}}) {
		numUids
	}
}
`

func UpdateRunHistoryDeploymentFields(
	ctx_ context.Context,
	client_ graphql.Client,
	runHistoryID *string,
	deploymentID string,
	sbomTool string,
	namespace string,
	account string,
	cluster string,
	application string,
	teamID string,
) (data_ *UpdateRunHistoryDeploymentFieldsResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "UpdateRunHistoryDeploymentFields",
		Query:  UpdateRunHistoryDeploymentFields_Operation,
		Variables: &__UpdateRunHistoryDeploymentFieldsInput{
			RunHistoryID: runHistoryID,
			DeploymentID: deploymentID,
			SbomTool:     sbomTool,
			Namespace:    namespace,
			Account:      account,
			Cluster:      cluster,
			Application:  application,
			TeamID:       teamID,
		},
	}

	data_ = &UpdateRunHistoryDeploymentFieldsResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}
