// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package december2024january2025

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

// SetDefaultValueOfHostingResponse is returned by SetDefaultValueOfHosting on success.
type SetDefaultValueOfHostingResponse struct {
	UpdateDeploymentTarget *SetDefaultValueOfHostingUpdateDeploymentTargetUpdateDeploymentTargetPayload `json:"updateDeploymentTarget"`
}

// GetUpdateDeploymentTarget returns SetDefaultValueOfHostingResponse.UpdateDeploymentTarget, and is useful for accessing the field via an interface.
func (v *SetDefaultValueOfHostingResponse) GetUpdateDeploymentTarget() *SetDefaultValueOfHostingUpdateDeploymentTargetUpdateDeploymentTargetPayload {
	return v.UpdateDeploymentTarget
}

// SetDefaultValueOfHostingUpdateDeploymentTargetUpdateDeploymentTargetPayload includes the requested fields of the GraphQL type UpdateDeploymentTargetPayload.
type SetDefaultValueOfHostingUpdateDeploymentTargetUpdateDeploymentTargetPayload struct {
	NumUids *int `json:"numUids"`
}

// GetNumUids returns SetDefaultValueOfHostingUpdateDeploymentTargetUpdateDeploymentTargetPayload.NumUids, and is useful for accessing the field via an interface.
func (v *SetDefaultValueOfHostingUpdateDeploymentTargetUpdateDeploymentTargetPayload) GetNumUids() *int {
	return v.NumUids
}

// The query or mutation executed by SetDefaultValueOfHosting.
const SetDefaultValueOfHosting_Operation = `
mutation SetDefaultValueOfHosting {
	updateDeploymentTarget(input: {set:{hosting:"self-hosted"},filter:{has:ip}}) {
		numUids
	}
}
`

func SetDefaultValueOfHosting(
	ctx_ context.Context,
	client_ graphql.Client,
) (*SetDefaultValueOfHostingResponse, error) {
	req_ := &graphql.Request{
		OpName: "SetDefaultValueOfHosting",
		Query:  SetDefaultValueOfHosting_Operation,
	}
	var err_ error

	var data_ SetDefaultValueOfHostingResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}
